const generateData = function(restaurantId, currentUserId) {
  return [
    {
      "orderAddress": "88 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
      "id": currentUserId
      },
      "deliveryDate": "2023-05-18"
    },
    {
      "orderAddress": "116 23rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-11-12"
    },
    {
      "orderAddress": "40 W Ocean Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-08-11"
    },
    {
      "orderAddress": "4134 Ten Hills",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-10-09"
    },
    {
      "orderAddress": "28 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-10-18"
    },
    {
      "orderAddress": "1408 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-25"
    },
    {
      "orderAddress": "50 E 5th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-07-18"
    },
    {
      "orderAddress": "231 N 23rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-11-12"
    },
    {
      "orderAddress": "32 W 17th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-07-12"
    },
    {
      "orderAddress": "89 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-07-22"
    },
    {
      "orderAddress": "37 2nd Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-06-29"
    },
    {
      "orderAddress": "6712 Park Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-13"
    },
    {
      "orderAddress": "68 N 73rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-10-20"
    },
    {
      "orderAddress": "40 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-10-13"
    },
    {
      "orderAddress": "94 E 4th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-01-16"
    },
    {
      "orderAddress": "74 58th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-01-12"
    },
    {
      "orderAddress": "42 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-14"
    },
    {
      "orderAddress": "5219 E 14th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-16"
    },
    {
      "orderAddress": "902 7th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-07-19"
    },
    {
      "orderAddress": "621 N 9th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-06-12"
    },
    {
      "orderAddress": "3542 W 93rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-13"
    },
    {
      "orderAddress": "9051 78th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-17"
    },
    {
      "orderAddress": "152 Ocean Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-03-31"
    },
    {
      "orderAddress": "37 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-03-24"
    },
    {
      "orderAddress": "431 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-22"
    },
    {
      "orderAddress": "98 Greenwood Blvd",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-12"
    },
    {
      "orderAddress": "428 S 27th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-08"
    },
    {
      "orderAddress": "56 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-19"
    },
    {
      "orderAddress": "1729 4th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-01-28"
    },
    {
      "orderAddress": "85 N 18th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-06-21"
    },
    {
      "orderAddress": "923 Oak St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-08"
    },
    {
      "orderAddress": "23114 Pine Dr",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-12"
    },
    {
      "orderAddress": "1823 Maple Dr",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-17"
    },
    {
      "orderAddress": "913 W 76th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-01"
    },
    {
      "orderAddress": "54 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-16"
    },
    {
      "orderAddress": "718 S 72rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-27"
    },
    {
      "orderAddress": "91 W 12th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-12"
    },
    {
      "orderAddress": "19343 Main St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-11-08"
    },
    {
      "orderAddress": "88 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-11-24"
    },
    {
      "orderAddress": "116 23rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-12-12"
    },
    {
      "orderAddress": "40 W Ocean Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-12-09"
    },
    {
      "orderAddress": "4134 Ten Hills",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-12-21"
    },
    {
      "orderAddress": "28 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-02-12"
    },
    {
      "orderAddress": "1408 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2022-02-16"
    },
    {
      "orderAddress": "50 E 5th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-18"
    },
    {
      "orderAddress": "231 N 23rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-20"
    },
    {
      "orderAddress": "32 W 17th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-14"
    },
    {
      "orderAddress": "89 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-07-16"
    },
    {
      "orderAddress": "37 2nd Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-07-19"
    },
    {
      "orderAddress": "6712 Park Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-07-17"
    },
    {
      "orderAddress": "68 N 73rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-12"
    },
    {
      "orderAddress": "40 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-19"
    },
    {
      "orderAddress": "94 E 4th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-15"
    },
    {
      "orderAddress": "74 58th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-10-14"
    },
    {
      "orderAddress": "42 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-11-18"
    },
    {
      "orderAddress": "5219 E 14th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-11-20"
    },
    {
      "orderAddress": "902 7th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-01-14"
    },
    {
      "orderAddress": "621 N 9th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-01-18"
    },
    {
      "orderAddress": "3542 W 93rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-03"
    },
    {
      "orderAddress": "9051 78th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-06-19"
    },
    {
      "orderAddress": "152 Ocean Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-03-28"
    },
    {
      "orderAddress": "37 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-09"
    },
    {
      "orderAddress": "431 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-14"
    },
    {
      "orderAddress": "98 Greenwood Blvd",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-21"
    },
    {
      "orderAddress": "428 S 27th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-07-19"
    },
    {
      "orderAddress": "56 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-10"
    },
    {
      "orderAddress": "1729 4th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-12"
    },
    {
      "orderAddress": "85 N 18th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-10-16"
    },
    {
      "orderAddress": "923 Oak St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-11-20"
    },
    {
      "orderAddress": "23114 Pine Dr",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-03-14"
    },
    {
      "orderAddress": "1823 Maple Dr",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-03-18"
    },
    {
      "orderAddress": "913 W 76th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-17"
    },
    {
      "orderAddress": "54 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-18"
    },
    {
      "orderAddress": "718 S 72rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-11"
    },
    {
      "orderAddress": "91 W 12th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-14"
    },
    {
      "orderAddress": "19343 Main St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-18"
    },
    {
      "orderAddress": "88 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-20"
    },
    {
      "orderAddress": "116 23rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-15"
    },
    {
      "orderAddress": "40 W Ocean Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-20"
    },
    {
      "orderAddress": "4134 Ten Hills",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-08-21"
    },
    {
      "orderAddress": "28 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-14"
    },
    {
      "orderAddress": "1408 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-09"
    },
    {
      "orderAddress": "50 E 5th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-18"
    },
    {
      "orderAddress": "231 N 23rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-24"
    },
    {
      "orderAddress": "32 W 17th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-09-18"
    },
    {
      "orderAddress": "89 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-06-21"
    },
    {
      "orderAddress": "37 2nd Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-06-20"
    },
    {
      "orderAddress": "6712 Park Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-06-28"
    },
    {
      "orderAddress": "68 N 73rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-06-17"
    },
    {
      "orderAddress": "40 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-13"
    },
    {
      "orderAddress": "94 E 4th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-12"
    },
    {
      "orderAddress": "74 58th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-05-17"
    },
    {
      "orderAddress": "42 Broadway",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-21"
    },
    {
      "orderAddress": "5219 E 14th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-14"
    },
    {
      "orderAddress": "902 7th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-28"
    },
    {
      "orderAddress": "621 N 9th Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-02-17"
    },
    {
      "orderAddress": "3542 W 93rd St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-24"
    },
    {
      "orderAddress": "9051 78th St",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-28"
    },
    {
      "orderAddress": "152 Ocean Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-23"
    },
    {
      "orderAddress": "37 Grand Ave",
      "restaurant": {
        "id": restaurantId
      },
      "createdBy": {
        "id": currentUserId
      },
      "deliveryDate": "2023-04-17"
    }
  ]
}

{
  "generateData": generateData
}